# Generated by Django 5.2.8 on 2025-11-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dateregistered', models.DateTimeField()),
                ('dob', models.DateTimeField()),
                ('medicalHistory', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
    ]
