# Generated by Django 5.2.8 on 2025-11-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myChapos', '0002_alter_patient_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('doctor', models.CharField()),
                ('diagnosis', models.TextField()),
                ('visitdate', models.DateField()),
            ],
        ),
    ]
